name: Java CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up openJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Build with Gradle
        run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 29807fd06bc18fbcd4bf1f7654306a9d1899486c92afd1851c30f8583804885d
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

